-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-02-07 15:37:08 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Artikal 
    ( 
     SifArt   NUMBER  NOT NULL , 
     OpisArt  VARCHAR2 (4000) , 
     NazivArt VARCHAR2 (30)  NOT NULL , 
     TipArt   VARCHAR2 (20)  NOT NULL , 
     VelArt   VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE Artikal 
    ADD CONSTRAINT Artikal_PK PRIMARY KEY ( SifArt ) ;

CREATE TABLE Cena 
    ( 
     CenaID         NUMBER  NOT NULL , 
     Iznos          NUMBER  NOT NULL , 
     DatPoc         VARCHAR2 (4000)  NOT NULL , 
     Vazeca         CHAR (1)  NOT NULL , 
     DatKr          DATE , 
     Artikal_SifArt NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Cena 
    ADD CONSTRAINT Cena_PK PRIMARY KEY ( Artikal_SifArt, CenaID ) ;

CREATE TABLE Cuva 
    ( 
     Proizvod_ProdID NUMBER  NOT NULL , 
     Magacin_LokID   NUMBER  NOT NULL , 
     Magacin_MagID   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Cuva 
    ADD CONSTRAINT Cuva_PK PRIMARY KEY ( Proizvod_ProdID, Magacin_LokID, Magacin_MagID ) ;

CREATE TABLE Distributer 
    ( 
     DisID      NUMBER  NOT NULL , 
     NazDis     VARCHAR2 (30)  NOT NULL , 
     KontaktDis VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE Distributer 
    ADD CONSTRAINT Distributer_PK PRIMARY KEY ( DisID ) ;

CREATE TABLE Dostava 
    ( 
     DosID      NUMBER  NOT NULL , 
     NazDos     VARCHAR2 (30)  NOT NULL , 
     KontaktDos VARCHAR2 (20)  NOT NULL 
    ) 
;

ALTER TABLE Dostava 
    ADD CONSTRAINT Dostava_PK PRIMARY KEY ( DosID ) ;

CREATE TABLE Izvestaj 
    ( 
     IzvID       NUMBER  NOT NULL , 
     DatKreir    DATE  NOT NULL , 
     TesktIzv    VARCHAR2 (4000)  NOT NULL , 
     Vlasnik_Mbv NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Izvestaj 
    ADD CONSTRAINT Izvestaj_PK PRIMARY KEY ( IzvID ) ;

CREATE TABLE Kasir 
    ( 
     Mbr NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Kasir 
    ADD CONSTRAINT Kasir_PK PRIMARY KEY ( Mbr ) ;

CREATE TABLE Lokal 
    ( 
     LokID NUMBER  NOT NULL , 
     Nazl  VARCHAR2 (30)  NOT NULL , 
     Tell  VARCHAR2 (20)  NOT NULL , 
     PIB   NUMBER  NOT NULL , 
     Kvad  INTEGER  NOT NULL , 
     Adrl  VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE Lokal 
    ADD CONSTRAINT Lokal_PK PRIMARY KEY ( LokID ) ;

CREATE TABLE Magacin 
    ( 
     MagID         NUMBER  NOT NULL , 
     Kvadmag       INTEGER  NOT NULL , 
     Lokal_LokID   NUMBER  NOT NULL , 
     Nabavka_NabID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Magacin 
    ADD CONSTRAINT Magacin_PK PRIMARY KEY ( Lokal_LokID, MagID ) ;

CREATE TABLE Meni 
    ( 
     MeniID      NUMBER  NOT NULL , 
     Jezikm      VARCHAR2 (4000)  NOT NULL , 
     Lokal_LokID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Meni 
    ADD 
    CHECK (VALUE IN {'SRPSKI','ENGLISH'}) 
;

ALTER TABLE Meni 
    ADD CONSTRAINT Meni_PK PRIMARY KEY ( MeniID ) ;

CREATE TABLE Musterija 
    ( 
     Mbm    NUMBER  NOT NULL , 
     Imem   VARCHAR2 (20)  NOT NULL , 
     Przm   VARCHAR2 (20)  NOT NULL , 
     Telm   VARCHAR2 (20)  NOT NULL , 
     Emailm VARCHAR2 (30) , 
     Adrm   VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE Musterija 
    ADD CONSTRAINT Musterija_PK PRIMARY KEY ( Mbm ) ;

CREATE TABLE Nabavka 
    ( 
     NabID                    NUMBER  NOT NULL , 
     DatNab                   DATE  NOT NULL , 
     IznosNab                 FLOAT  NOT NULL , 
     StatusNab                VARCHAR2 (20)  NOT NULL , 
     Zaposljava_Zaposljava_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Nabavka 
    ADD CONSTRAINT Nabavka_PK PRIMARY KEY ( NabID ) ;

CREATE TABLE Namirnica 
    ( 
     NamID              NUMBER  NOT NULL , 
     NazNam             VARCHAR2 (30)  NOT NULL , 
     OpisNam            VARCHAR2 (4000) , 
     Jedinica           VARCHAR2 (20)  NOT NULL , 
     Pomocni_Radnik_Mbr NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Namirnica 
    ADD CONSTRAINT Namirnica_PK PRIMARY KEY ( NamID ) ;

CREATE TABLE Obavlja 
    ( 
     Distributer_DisID NUMBER  NOT NULL , 
     Nabavka_NabID     NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Obavlja 
    ADD CONSTRAINT Obavlja_PK PRIMARY KEY ( Distributer_DisID, Nabavka_NabID ) ;

CREATE TABLE Obuhvata 
    ( 
     Izvestaj_IzvID   NUMBER  NOT NULL , 
     Porudzbina_PorID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Obuhvata 
    ADD CONSTRAINT Obuhvata_PK PRIMARY KEY ( Izvestaj_IzvID, Porudzbina_PorID ) ;

CREATE TABLE Pica_Majstor 
    ( 
     Mbr    NUMBER  NOT NULL , 
     GodIsk INTEGER  NOT NULL , 
     Zvanje VARCHAR2 (30)  NOT NULL 
    ) 
;

ALTER TABLE Pica_Majstor 
    ADD CONSTRAINT Pica_Majstor_PK PRIMARY KEY ( Mbr ) ;

CREATE TABLE Pomocni_Radnik 
    ( 
     Mbr NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Pomocni_Radnik 
    ADD CONSTRAINT Pomocni_Radnik_PK PRIMARY KEY ( Mbr ) ;

CREATE TABLE Porudzbina 
    ( 
     PorID         NUMBER  NOT NULL , 
     DatVrPor      DATE  NOT NULL , 
     StatusPor     VARCHAR2 (20)  NOT NULL , 
     Suma          FLOAT  NOT NULL , 
     NacPreuz      VARCHAR2 (20)  NOT NULL , 
     Kasir_Mbr     NUMBER  NOT NULL , 
     Musterija_Mbm NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Porudzbina 
    ADD 
    CHECK (VALUE IN ('CEKANJE', 'PRAVI_SE', 'PREUZETA')) 
;

ALTER TABLE Porudzbina 
    ADD 
    CHECK (VALUE IN {'KASIR','PICA_MAJSTOR','POMOCNI_RADNIK'}) 
;

ALTER TABLE Porudzbina 
    ADD CONSTRAINT Porudzbina_PK PRIMARY KEY ( PorID ) ;

CREATE TABLE Poseduje 
    ( 
     Vlasnik_Mbv NUMBER  NOT NULL , 
     Lokal_LokID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Poseduje 
    ADD CONSTRAINT Poseduje_PK PRIMARY KEY ( Vlasnik_Mbv, Lokal_LokID ) ;

CREATE TABLE Proizvod 
    ( 
     ProdID NUMBER  NOT NULL , 
     Nazp   VARCHAR2 (30)  NOT NULL , 
     Wght   FLOAT  NOT NULL , 
     Roktr  DATE  NOT NULL 
    ) 
;

ALTER TABLE Proizvod 
    ADD CONSTRAINT Proizvod_PK PRIMARY KEY ( ProdID ) ;

CREATE TABLE Racun 
    ( 
     RacID     NUMBER  NOT NULL , 
     NacPl     VARCHAR2 (20)  NOT NULL , 
     DatVrRac  DATE  NOT NULL , 
     Izn       NUMBER , 
     Kasir_Mbr NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Racun 
    ADD 
    CHECK (VALUE IN ('GOTOVINA', 'PLATNA_KARITCA', 'PRENOS_NA_RACUN')) 
;

ALTER TABLE Racun 
    ADD CONSTRAINT Racun_PK PRIMARY KEY ( RacID ) ;

CREATE TABLE Radnik 
    ( 
     Mbr        NUMBER  NOT NULL , 
     Imer       VARCHAR2 (20)  NOT NULL , 
     Przr       VARCHAR2 (20)  NOT NULL , 
     Datr       DATE  NOT NULL , 
     Emailr     VARCHAR2 (30) , 
     Telr       VARCHAR2 (20)  NOT NULL , 
     DatSan     DATE  NOT NULL , 
     Tipr       VARCHAR2 (20)  NOT NULL , 
     Radnik_Mbr NUMBER 
    ) 
;

ALTER TABLE Radnik 
    ADD 
    CHECK (VALUE IN {'KASIR','PICA_MAJSTOR','POMOCNI_RADNIK'}) 
;

ALTER TABLE Radnik 
    ADD CONSTRAINT Radnik_PK PRIMARY KEY ( Mbr ) ;

CREATE TABLE Sadrzan 
    ( 
     Proizvod_ProdID NUMBER  NOT NULL , 
     Nabavka_NabID   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Sadrzan 
    ADD CONSTRAINT Sadrzan_PK PRIMARY KEY ( Proizvod_ProdID, Nabavka_NabID ) ;

CREATE TABLE Sadrzi 
    ( 
     Meni_MeniID    NUMBER  NOT NULL , 
     Artikal_SifArt NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Sadrzi 
    ADD CONSTRAINT Sadrzi_PK PRIMARY KEY ( Meni_MeniID, Artikal_SifArt ) ;

CREATE TABLE Saradjuje 
    ( 
     Lokal_LokID   NUMBER  NOT NULL , 
     Dostava_DosID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Saradjuje 
    ADD CONSTRAINT Saradjuje_PK PRIMARY KEY ( Lokal_LokID, Dostava_DosID ) ;

CREATE TABLE Sastavljen 
    ( 
     Artikal_SifArt  NUMBER  NOT NULL , 
     Namirnica_NamID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Sastavljen 
    ADD CONSTRAINT Sastavljen_PK PRIMARY KEY ( Artikal_SifArt, Namirnica_NamID ) ;

CREATE TABLE Stavka 
    ( 
     StvID            NUMBER  NOT NULL , 
     KolStv           NUMBER  NOT NULL , 
     Porudzbina_PorID NUMBER  NOT NULL , 
     Pica_Majstor_Mbr NUMBER  NOT NULL , 
     Artikal_SifArt   NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Stavka 
    ADD CONSTRAINT Stavka_PK PRIMARY KEY ( Porudzbina_PorID, StvID ) ;

CREATE TABLE Trosi 
    ( 
     Namirnica_NamID NUMBER  NOT NULL , 
     Proizvod_ProdID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Trosi 
    ADD CONSTRAINT Trosi_PK PRIMARY KEY ( Namirnica_NamID, Proizvod_ProdID ) ;

CREATE TABLE Vlasnik 
    ( 
     Mbv    NUMBER  NOT NULL , 
     Telv   VARCHAR2 (20)  NOT NULL , 
     Imev   VARCHAR2 (20)  NOT NULL , 
     Przv   VARCHAR2 (20)  NOT NULL , 
     Emailv VARCHAR2 (20) 
    ) 
;

ALTER TABLE Vlasnik 
    ADD CONSTRAINT Vlasnik_PK PRIMARY KEY ( Mbv ) ;

CREATE TABLE Zaposljava 
    ( 
     DatZap        DATE  NOT NULL , 
     DatDo         DATE , 
     Pozicija      VARCHAR2 (20)  NOT NULL , 
     Radnik_Mbr    NUMBER  NOT NULL , 
     Lokal_LokID   NUMBER  NOT NULL , 
     Zaposljava_ID NUMBER  NOT NULL 
    ) 
;

ALTER TABLE Zaposljava 
    ADD 
    CHECK (VALUE IN {'KASIR','PICA_MAJSTOR','POMOCNI_RADNIK'}) 
;

ALTER TABLE Zaposljava 
    ADD CONSTRAINT Zaposljava_PK PRIMARY KEY ( Zaposljava_ID ) ;

ALTER TABLE Cena 
    ADD CONSTRAINT Cena_Artikal_FK FOREIGN KEY 
    ( 
     Artikal_SifArt
    ) 
    REFERENCES Artikal 
    ( 
     SifArt
    ) 
;

ALTER TABLE Cuva 
    ADD CONSTRAINT Cuva_Magacin_FK FOREIGN KEY 
    ( 
     Magacin_LokID,
     Magacin_MagID
    ) 
    REFERENCES Magacin 
    ( 
     Lokal_LokID,
     MagID
    ) 
;

ALTER TABLE Cuva 
    ADD CONSTRAINT Cuva_Proizvod_FK FOREIGN KEY 
    ( 
     Proizvod_ProdID
    ) 
    REFERENCES Proizvod 
    ( 
     ProdID
    ) 
;

ALTER TABLE Izvestaj 
    ADD CONSTRAINT Izvestaj_Vlasnik_FK FOREIGN KEY 
    ( 
     Vlasnik_Mbv
    ) 
    REFERENCES Vlasnik 
    ( 
     Mbv
    ) 
;

ALTER TABLE Kasir 
    ADD CONSTRAINT Kasir_Radnik_FK FOREIGN KEY 
    ( 
     Mbr
    ) 
    REFERENCES Radnik 
    ( 
     Mbr
    ) 
;

ALTER TABLE Magacin 
    ADD CONSTRAINT Magacin_Lokal_FK FOREIGN KEY 
    ( 
     Lokal_LokID
    ) 
    REFERENCES Lokal 
    ( 
     LokID
    ) 
;

ALTER TABLE Magacin 
    ADD CONSTRAINT Magacin_Nabavka_FK FOREIGN KEY 
    ( 
     Nabavka_NabID
    ) 
    REFERENCES Nabavka 
    ( 
     NabID
    ) 
;

ALTER TABLE Meni 
    ADD CONSTRAINT Meni_Lokal_FK FOREIGN KEY 
    ( 
     Lokal_LokID
    ) 
    REFERENCES Lokal 
    ( 
     LokID
    ) 
;

ALTER TABLE Nabavka 
    ADD CONSTRAINT Nabavka_Zaposljava_FK FOREIGN KEY 
    ( 
     Zaposljava_Zaposljava_ID
    ) 
    REFERENCES Zaposljava 
    ( 
     Zaposljava_ID
    ) 
;

ALTER TABLE Namirnica 
    ADD CONSTRAINT Namirnica_Pomocni_Radnik_FK FOREIGN KEY 
    ( 
     Pomocni_Radnik_Mbr
    ) 
    REFERENCES Pomocni_Radnik 
    ( 
     Mbr
    ) 
;

ALTER TABLE Obavlja 
    ADD CONSTRAINT Obavlja_Distributer_FK FOREIGN KEY 
    ( 
     Distributer_DisID
    ) 
    REFERENCES Distributer 
    ( 
     DisID
    ) 
;

ALTER TABLE Obavlja 
    ADD CONSTRAINT Obavlja_Nabavka_FK FOREIGN KEY 
    ( 
     Nabavka_NabID
    ) 
    REFERENCES Nabavka 
    ( 
     NabID
    ) 
;

ALTER TABLE Obuhvata 
    ADD CONSTRAINT Obuhvata_Izvestaj_FK FOREIGN KEY 
    ( 
     Izvestaj_IzvID
    ) 
    REFERENCES Izvestaj 
    ( 
     IzvID
    ) 
;

ALTER TABLE Obuhvata 
    ADD CONSTRAINT Obuhvata_Porudzbina_FK FOREIGN KEY 
    ( 
     Porudzbina_PorID
    ) 
    REFERENCES Porudzbina 
    ( 
     PorID
    ) 
;

ALTER TABLE Pica_Majstor 
    ADD CONSTRAINT Pica_Majstor_Radnik_FK FOREIGN KEY 
    ( 
     Mbr
    ) 
    REFERENCES Radnik 
    ( 
     Mbr
    ) 
;

ALTER TABLE Pomocni_Radnik 
    ADD CONSTRAINT Pomocni_Radnik_Radnik_FK FOREIGN KEY 
    ( 
     Mbr
    ) 
    REFERENCES Radnik 
    ( 
     Mbr
    ) 
;

ALTER TABLE Porudzbina 
    ADD CONSTRAINT Porudzbina_Kasir_FK FOREIGN KEY 
    ( 
     Kasir_Mbr
    ) 
    REFERENCES Kasir 
    ( 
     Mbr
    ) 
;

ALTER TABLE Porudzbina 
    ADD CONSTRAINT Porudzbina_Musterija_FK FOREIGN KEY 
    ( 
     Musterija_Mbm
    ) 
    REFERENCES Musterija 
    ( 
     Mbm
    ) 
;

ALTER TABLE Poseduje 
    ADD CONSTRAINT Poseduje_Lokal_FK FOREIGN KEY 
    ( 
     Lokal_LokID
    ) 
    REFERENCES Lokal 
    ( 
     LokID
    ) 
;

ALTER TABLE Poseduje 
    ADD CONSTRAINT Poseduje_Vlasnik_FK FOREIGN KEY 
    ( 
     Vlasnik_Mbv
    ) 
    REFERENCES Vlasnik 
    ( 
     Mbv
    ) 
;

ALTER TABLE Racun 
    ADD CONSTRAINT Racun_Kasir_FK FOREIGN KEY 
    ( 
     Kasir_Mbr
    ) 
    REFERENCES Kasir 
    ( 
     Mbr
    ) 
;

ALTER TABLE Radnik 
    ADD CONSTRAINT Radnik_Radnik_FK FOREIGN KEY 
    ( 
     Radnik_Mbr
    ) 
    REFERENCES Radnik 
    ( 
     Mbr
    ) 
;

ALTER TABLE Sadrzan 
    ADD CONSTRAINT Sadrzan_Nabavka_FK FOREIGN KEY 
    ( 
     Nabavka_NabID
    ) 
    REFERENCES Nabavka 
    ( 
     NabID
    ) 
;

ALTER TABLE Sadrzan 
    ADD CONSTRAINT Sadrzan_Proizvod_FK FOREIGN KEY 
    ( 
     Proizvod_ProdID
    ) 
    REFERENCES Proizvod 
    ( 
     ProdID
    ) 
;

ALTER TABLE Sadrzi 
    ADD CONSTRAINT Sadrzi_Artikal_FK FOREIGN KEY 
    ( 
     Artikal_SifArt
    ) 
    REFERENCES Artikal 
    ( 
     SifArt
    ) 
;

ALTER TABLE Sadrzi 
    ADD CONSTRAINT Sadrzi_Meni_FK FOREIGN KEY 
    ( 
     Meni_MeniID
    ) 
    REFERENCES Meni 
    ( 
     MeniID
    ) 
;

ALTER TABLE Saradjuje 
    ADD CONSTRAINT Saradjuje_Dostava_FK FOREIGN KEY 
    ( 
     Dostava_DosID
    ) 
    REFERENCES Dostava 
    ( 
     DosID
    ) 
;

ALTER TABLE Saradjuje 
    ADD CONSTRAINT Saradjuje_Lokal_FK FOREIGN KEY 
    ( 
     Lokal_LokID
    ) 
    REFERENCES Lokal 
    ( 
     LokID
    ) 
;

ALTER TABLE Sastavljen 
    ADD CONSTRAINT Sastavljen_Artikal_FK FOREIGN KEY 
    ( 
     Artikal_SifArt
    ) 
    REFERENCES Artikal 
    ( 
     SifArt
    ) 
;

ALTER TABLE Sastavljen 
    ADD CONSTRAINT Sastavljen_Namirnica_FK FOREIGN KEY 
    ( 
     Namirnica_NamID
    ) 
    REFERENCES Namirnica 
    ( 
     NamID
    ) 
;

ALTER TABLE Stavka 
    ADD CONSTRAINT Stavka_Artikal_FK FOREIGN KEY 
    ( 
     Artikal_SifArt
    ) 
    REFERENCES Artikal 
    ( 
     SifArt
    ) 
;

ALTER TABLE Stavka 
    ADD CONSTRAINT Stavka_Pica_Majstor_FK FOREIGN KEY 
    ( 
     Pica_Majstor_Mbr
    ) 
    REFERENCES Pica_Majstor 
    ( 
     Mbr
    ) 
;

ALTER TABLE Stavka 
    ADD CONSTRAINT Stavka_Porudzbina_FK FOREIGN KEY 
    ( 
     Porudzbina_PorID
    ) 
    REFERENCES Porudzbina 
    ( 
     PorID
    ) 
;

ALTER TABLE Trosi 
    ADD CONSTRAINT Trosi_Namirnica_FK FOREIGN KEY 
    ( 
     Namirnica_NamID
    ) 
    REFERENCES Namirnica 
    ( 
     NamID
    ) 
;

ALTER TABLE Trosi 
    ADD CONSTRAINT Trosi_Proizvod_FK FOREIGN KEY 
    ( 
     Proizvod_ProdID
    ) 
    REFERENCES Proizvod 
    ( 
     ProdID
    ) 
;

ALTER TABLE Zaposljava 
    ADD CONSTRAINT Zaposljava_Lokal_FK FOREIGN KEY 
    ( 
     Lokal_LokID
    ) 
    REFERENCES Lokal 
    ( 
     LokID
    ) 
;

ALTER TABLE Zaposljava 
    ADD CONSTRAINT Zaposljava_Radnik_FK FOREIGN KEY 
    ( 
     Radnik_Mbr
    ) 
    REFERENCES Radnik 
    ( 
     Mbr
    ) 
;

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated 

--  ERROR: No Discriminator Column found in Arc FKArc_1 - constraint trigger for Arc cannot be generated

CREATE SEQUENCE Zaposljava_Zaposljava_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER Zaposljava_Zaposljava_ID_TRG 
BEFORE INSERT ON Zaposljava 
FOR EACH ROW 
WHEN (NEW.Zaposljava_ID IS NULL) 
BEGIN 
    :NEW.Zaposljava_ID := Zaposljava_Zaposljava_ID_SEQ.NEXTVAL; 
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            30
-- CREATE INDEX                             0
-- ALTER TABLE                             73
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   3
-- WARNINGS                                 0
